import React from 'react';
function Header(){
 return(
    <div className="w-[11/12] max-w-400 mx-auto ">
        ndoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceowncendoehncjencnecnewncuiohefnwiuencewncjewnehnecineiceownce
    </div>
 );
};
export default Header; 